# version: '3'

# services:
#   db:
#     platform: linux/x86_64
#     image: mysql:8-debian
#     container_name: aiesl-db
#     restart: always
#     environment:
#       MYSQL_DATABASE: aidb
#       MYSQL_USER: 'aidb'
#       MYSQL_PASSWORD: 'aidb'
#       MYSQL_ROOT_PASSWORD: 'aidb'
#     ports:
#       - "3306:3306"
#     volumes:
#       - /tmp/app/mysqld:/var/run/mysqld
#       - ./db:/var/lib/mysql
#     networks:
#       - mynetwork

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#       - /tmp/app/mysqld:/run/mysqld
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     networks:
#       - mynetwork

# volumes:
#   db:

# networks:
#   mynetwork:


version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8-debian
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db




