# Generated by Django 3.0.7 on 2023-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(db_column='S.No', max_length=5)),
                ('arrival_flight', models.CharField(db_column='Arrival', max_length=10)),
                ('arrival_from', models.CharField(db_column='From', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(db_column='Date', max_length=20)),
                ('Employee_name', models.CharField(db_column='Employee_name', max_length=25)),
                ('Employee_sap', models.CharField(db_column='Employee_sap', max_length=25)),
                ('Group', models.CharField(db_column='Group', max_length=25)),
                ('Attendance', models.CharField(db_column='Attendance', max_length=25)),
                ('Shift', models.CharField(db_column='Shift', max_length=25)),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('empname', models.CharField(blank=True, db_column='Empname', max_length=25, null=True)),
                ('sap', models.IntegerField(db_column='SAP', primary_key=True, serialize=False)),
                ('designation', models.CharField(db_column='Designation', max_length=25)),
                ('mob', models.CharField(db_column='Mob', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('trained', models.CharField(db_column='Trained', max_length=10)),
                ('grp', models.CharField(db_column='Grp', max_length=10)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('F', models.AutoField(db_column='F', primary_key=True, serialize=False)),
                ('flight_no_arr', models.CharField(db_column='Flight_no_arr', max_length=25)),
                ('flight_no_dep', models.CharField(blank=True, db_column='Flight_no_dep', max_length=25, null=True)),
                ('sta', models.IntegerField(db_column='STA')),
                ('std', models.IntegerField(blank=True, db_column='STD', null=True)),
                ('arrival_days', models.CharField(db_column='Arrival_days', max_length=50)),
                ('departure_days', models.CharField(blank=True, db_column='Departure_days', max_length=50, null=True)),
                ('destination_from', models.CharField(max_length=25)),
                ('destination_to', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'FlightSchedule',
            },
        ),
    ]
