# Generated by Django 4.1.5 on 2023-02-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaieslapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departureschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={},
        ),
    ]
