# Generated by Django 4.1.5 on 2023-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaieslapp', '0005_rename_id_departureschedule_id_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_no_arr', models.CharField(db_column='Flight_no_arr', max_length=25)),
                ('flight_no_dep', models.CharField(blank=True, db_column='Flight_no_dep', max_length=25, null=True)),
                ('sta', models.CharField(db_column='STA', max_length=25)),
                ('std', models.CharField(blank=True, db_column='STD', max_length=25, null=True)),
                ('arrival_days', models.CharField(db_column='Arrival_days', max_length=25)),
                ('departure_days', models.CharField(blank=True, db_column='Departure_days', max_length=25, null=True)),
                ('destination_from', models.CharField(max_length=25)),
                ('destination_to', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'FlightSchedule',
            },
        ),
        migrations.DeleteModel(
            name='Arrivalschedule',
        ),
        migrations.DeleteModel(
            name='Departureschedule',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees',
            name='sap',
            field=models.IntegerField(db_column='SAP', primary_key=True, serialize=False),
        ),
    ]
