# Generated by Django 3.2.18 on 2023-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaieslapp', '0006_flightschedule_delete_arrivalschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(db_column='Date', max_length=20)),
                ('Employee_name', models.CharField(db_column='Employee_name', max_length=25)),
                ('Employee_sap', models.CharField(db_column='Employee_sap', max_length=25)),
                ('Group', models.CharField(db_column='Group', max_length=25)),
                ('Attendance', models.CharField(db_column='Attendance', max_length=25)),
                ('Shift', models.CharField(db_column='Shift', max_length=25)),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.RemoveField(
            model_name='flightschedule',
            name='id',
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='F',
            field=models.AutoField(db_column='F', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='arrival_days',
            field=models.CharField(db_column='Arrival_days', max_length=50),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='departure_days',
            field=models.CharField(blank=True, db_column='Departure_days', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='sta',
            field=models.IntegerField(db_column='STA'),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='std',
            field=models.IntegerField(blank=True, db_column='STD', null=True),
        ),
    ]
